// HeavyThing x86_64 assembly language library — Rust translation.
//
// Rust translation © 2026, licensed under GPL-3.0-or-later.
// Derived from the HeavyThing assembly library:
//   Copyright © 2015–2018 2 Ton Digital, Jeff Marrison <info@2ton.com.au>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Integration tests for the `heavything::tui` subsystem.
//!
//! These tests exercise the public API surface of the TUI subsystem from
//! an external-consumer perspective (the `tests/` directory produces a
//! separate compilation unit that links against the `heavything` library
//! as if it were any downstream crate). Per AAP §0.3.1.2 they verify
//! "rendered-frame byte comparison against expected ANSI" so the byte
//! stream generated by widget composition is checked against the
//! exact escape sequences specified in the FASM `tui_render.inc` /
//! `tui_ansi.inc` reference.
//!
//! The 18 tests are organized into 8 sections matching the QA
//! checkpoint Phase 2 scope:
//!
//! | Section | Purpose | Test Count |
//! |---------|---------|-----------|
//! | 1. ANSI Constants | Byte-literal verification of ALT_SCREEN_ENTER, ALT_SCREEN_EXIT, CURSOR_HOME, CLEAR_SCREEN, ACS_ENTER/EXIT, SGR_RESET | 5 |
//! | 2. Geometry | Point + Rect API with half-open semantics, intersect, contains, align_offset | 5 |
//! | 3. Widget Tree | TuiBackground draw composition + TuiVLine/TuiHLine factory verification | 2 |
//! | 4. ACS Lines | VLINE_CHAR=0x2502 / HLINE_CHAR=0x2500 stored verbatim in line widgets | 1 |
//! | 5. Alt-Screen Mode | TERMINAL_ALTERNATESCREEN=true config; ALT_SCREEN_ENTER/EXIT byte equality | 2 |
//! | 6. Raw Terminal | WindowSize struct semantics; RawTerminal::exit_pending() default state | 1 |
//! | 7. Background Widget | TuiBackground field accessors + initialization invariants | 1 |
//! | 8. TuiError | Variant construction + Display formatting for all three io::Error variants | 1 |
//!
//! ## Test infrastructure: `TestSink`
//!
//! The `TestSink` struct used by `tui::render` unit tests is private to
//! that module's `#[cfg(test)] mod tests` block, which means it cannot
//! be re-imported from this integration test crate. We therefore provide
//! a minimal local re-implementation that captures every byte written
//! via `Renderer::ansi_output` into a `Vec<u8>`. This lets us verify the
//! exact ANSI byte sequences the renderer emits, which is the spirit of
//! AAP §0.3.1.2's "rendered-frame byte comparison".
//!
//! ## Critical constraint: no `RawTerminal::enter()` calls
//!
//! `RawTerminal` is a process-wide singleton enforced by an `OnceLock`
//! [`INIT_GUARD`](heavything::tui::terminal); calling `enter()` here
//! would conflict with the `test_raw_terminal_roundtrip` test in
//! `ffi_boundary.rs` and break parallel test execution. This file
//! therefore only verifies non-syscalling invariants of `WindowSize`,
//! `RawTerminal::exit_pending()` (an associated function, not a
//! method), and the Drop-aware byte sequences that `RawTerminal::enter`
//! and `Drop` emit (verified at the constant level via the `ansi`
//! module).

#![allow(clippy::unwrap_used)]

use std::sync::Arc;

use heavything::config;
use heavything::error::TuiError;
use heavything::tui::ansi;
use heavything::tui::geometry::{align_offset, Point, Rect};
use heavything::tui::object::{ColorPair, Widget};
use heavything::tui::render::{RenderState, Renderer};
use heavything::tui::terminal::{RawTerminal, WindowSize};
use heavything::tui::widgets::background::TuiBackground;
use heavything::tui::widgets::lines::{TuiHLine, TuiVLine, HLINE_CHAR, VLINE_CHAR};

// ============================================================================
// Local TestSink — minimal `Renderer` implementation for byte capture.
//
// The `TestSink` in `tui/render.rs` is gated behind `#[cfg(test)] mod
// tests`, so external integration tests cannot reuse it. We provide an
// API-equivalent re-implementation here. Its sole job is to capture every
// byte the renderer emits via `ansi_output` so tests can assert exact
// equality with expected ANSI byte sequences.
// ============================================================================

/// Test-only `Renderer` implementation that captures emitted bytes
/// into an in-memory `Vec<u8>`.
///
/// This struct is intentionally minimal — it implements only the four
/// required methods of the `Renderer` trait and relies on the trait's
/// default implementations for `move_cursor`, `set_fg`, `set_bg`,
/// `set_attr`, `set_acs`, `write_text`, `clear_screen`, etc.
struct TestSink {
    /// Captured bytes — every `ansi_output` call appends here.
    out: Vec<u8>,
    /// Cached render state per the trait contract.
    state: RenderState,
    /// Number of `flush()` calls invoked (some tests verify this).
    flush_count: u32,
}

impl TestSink {
    /// Construct a fresh sink with default state and an empty byte buffer.
    fn new() -> Self {
        Self {
            out: Vec::new(),
            state: RenderState::default(),
            flush_count: 0,
        }
    }
}

impl Renderer for TestSink {
    fn ansi_output(&mut self, bytes: &[u8]) -> Result<(), TuiError> {
        self.out.extend_from_slice(bytes);
        Ok(())
    }

    fn flush(&mut self) -> Result<(), TuiError> {
        self.flush_count += 1;
        Ok(())
    }

    fn state(&self) -> &RenderState {
        &self.state
    }

    fn state_mut(&mut self) -> &mut RenderState {
        &mut self.state
    }
}

// ============================================================================
// Section 1: ANSI Constants (5 tests)
//
// These tests verify the byte-literal values of every ANSI escape
// sequence constant the FASM TUI relies on. The constants must match
// `tui_ansi.inc` and `tui_terminal.inc` byte-for-byte; any drift would
// cause incompatible escape sequences to reach the terminal.
// ============================================================================

#[test]
fn test_ansi_alt_screen_enter_exit_byte_equality() {
    // Per FASM `tui_terminal.inc` lines 308–316 the alternate-screen
    // enter/exit sequences are exactly `ESC[?1049h` (8 bytes) and
    // `ESC[?1049l` (8 bytes). The Rust port must preserve these exact
    // byte streams because terminals interpret ?1049h/l as a privilege-
    // mode toggle and any divergence would either fail to enter the
    // alternate buffer or fail to restore on exit.
    assert_eq!(ansi::ALT_SCREEN_ENTER, b"\x1b[?1049h");
    assert_eq!(ansi::ALT_SCREEN_EXIT, b"\x1b[?1049l");
    assert_eq!(ansi::ALT_SCREEN_ENTER.len(), 8);
    assert_eq!(ansi::ALT_SCREEN_EXIT.len(), 8);
}

#[test]
fn test_ansi_cursor_constants_byte_equality() {
    // FASM `tui_render.inc` emits `ESC[H` (3 bytes) for "cursor home"
    // and `ESC[2J` (4 bytes) for "clear screen". These are the
    // canonical CSI sequences. The hide/show cursor sequences are
    // `ESC[?25l` and `ESC[?25h` (6 bytes each) per VT100 / xterm
    // private-mode 25.
    assert_eq!(ansi::CURSOR_HOME, b"\x1b[H");
    assert_eq!(ansi::CLEAR_SCREEN, b"\x1b[2J");
    assert_eq!(ansi::HIDE_CURSOR, b"\x1b[?25l");
    assert_eq!(ansi::SHOW_CURSOR, b"\x1b[?25h");
}

#[test]
fn test_ansi_acs_bracket_byte_equality() {
    // VT100 ACS (Alternate Character Set) bracket sequences:
    //   ESC ( 0  → enter ACS (G0 set is line-drawing)
    //   ESC ( B  → exit  ACS (G0 set is US-ASCII)
    // FASM `tui_render.inc` set_acs emits these to gate Unicode line
    // codepoints (0x2500/0x2502) into the corresponding VT100 ACS
    // glyphs (`q` / `x`) when ACS_LINECHARS = true.
    assert_eq!(ansi::ACS_ENTER, b"\x1b(0");
    assert_eq!(ansi::ACS_EXIT, b"\x1b(B");
    assert_eq!(ansi::ACS_ENTER.len(), 3);
    assert_eq!(ansi::ACS_EXIT.len(), 3);
}

#[test]
fn test_ansi_sgr_reset_and_attribute_constants() {
    // SGR reset returns the terminal to its default attribute state.
    // FASM emits this between widget redraws so per-cell attributes
    // do not bleed across widgets.
    assert_eq!(ansi::SGR_RESET, b"\x1b[0m");
    assert_eq!(ansi::SGR_BOLD, b"\x1b[1m");
    assert_eq!(ansi::SGR_DIM, b"\x1b[2m");
    assert_eq!(ansi::SGR_UNDERLINE, b"\x1b[4m");
    assert_eq!(ansi::SGR_REVERSE, b"\x1b[7m");
    assert_eq!(ansi::SGR_BLINK, b"\x1b[5m");
}

#[test]
fn test_ansi_clear_line_and_csi_prefix() {
    // Auxiliary clear / control-sequence-introducer constants used by
    // various widgets. CSI is the universal `ESC[` prefix; ESC alone
    // is the bare `\x1b` escape character used by ACS bracket
    // sequences (which use `ESC(...)` rather than `ESC[...]`).
    assert_eq!(ansi::CSI, b"\x1b[");
    assert_eq!(ansi::ESC, b"\x1b");
    assert_eq!(ansi::CLEAR_LINE, b"\x1b[2K");
    assert_eq!(ansi::CLEAR_TO_EOL, b"\x1b[K");
    assert_eq!(ansi::CLEAR_TO_EOS, b"\x1b[J");
}

// ============================================================================
// Section 2: Geometry (5 tests)
//
// These tests exercise Point and Rect primitives with the half-open
// rectangle convention specified by FASM `tui_geometry.inc`. The (ax,
// ay) corner is inclusive while (bx, by) is exclusive so width =
// bx - ax and height = by - ay.
// ============================================================================

#[test]
fn test_geometry_point_basic_operations() {
    // Construction + ZERO sentinel + translated + non-negative test.
    let zero = Point::ZERO;
    assert_eq!(zero.x, 0);
    assert_eq!(zero.y, 0);
    assert!(zero.is_non_negative());

    let p = Point::new(5, 7);
    assert_eq!(p.x, 5);
    assert_eq!(p.y, 7);
    assert!(p.is_non_negative());

    // translated returns a new point shifted by (dx, dy)
    let q = p.translated(3, -2);
    assert_eq!(q, Point::new(8, 5));

    // Point with a negative coordinate is not non-negative.
    let neg = Point::new(-1, 4);
    assert!(!neg.is_non_negative());
}

#[test]
fn test_geometry_rect_from_origin_size_and_dimensions() {
    // from_origin_size produces a half-open rect: ax/ay = origin,
    // bx/by = origin + size. The width()/height() accessors must
    // therefore equal the original size arguments.
    let r = Rect::from_origin_size(Point::new(2, 3), 10, 5);
    assert_eq!(r.ax, 2);
    assert_eq!(r.ay, 3);
    assert_eq!(r.bx, 12); // 2 + 10
    assert_eq!(r.by, 8); // 3 + 5
    assert_eq!(r.width(), 10);
    assert_eq!(r.height(), 5);

    // area = width * height (Rect::area, NOT Size::area — geometry
    // module exposes only Rect-rooted area per AAP §0.4.4).
    assert_eq!(r.area(), 50);

    // Empty rect (width or height = 0) reports zero area.
    let empty = Rect::EMPTY;
    assert_eq!(empty.area(), 0);
    assert!(empty.is_empty());

    // Negative-width rects clamp to 0 — this matches FASM behavior
    // when `bx < ax` (e.g. an inverted intersection).
    let inverted = Rect::new(10, 0, 5, 4);
    assert_eq!(inverted.width(), 0);
    assert_eq!(inverted.height(), 4);
}

#[test]
fn test_geometry_rect_intersect_and_union() {
    // Two overlapping rects intersect to their common region.
    let a = Rect::new(0, 0, 10, 10);
    let b = Rect::new(5, 5, 15, 15);
    let i = a.intersect(b);
    assert_eq!(i, Rect::new(5, 5, 10, 10));

    // Disjoint rects intersect to EMPTY.
    let c = Rect::new(0, 0, 5, 5);
    let d = Rect::new(10, 10, 20, 20);
    assert_eq!(c.intersect(d), Rect::EMPTY);

    // Union of two overlapping rects is the smallest covering rect.
    let u = a.union(b);
    assert_eq!(u, Rect::new(0, 0, 15, 15));

    // Union with EMPTY returns the non-empty operand.
    assert_eq!(a.union(Rect::EMPTY), a);
    assert_eq!(Rect::EMPTY.union(a), a);
}

#[test]
fn test_geometry_rect_contains_point_and_rect() {
    // Half-open semantics: bx and by are *exclusive* so a 10×5 rect
    // at origin (0,0) contains points up to (9, 4) but not (10, 4).
    let r = Rect::new(0, 0, 10, 5);
    assert!(r.contains(Point::new(0, 0)), "(0,0) should be contained");
    assert!(r.contains(Point::new(9, 4)), "(9,4) should be contained");

    // Boundary checks — exclusive side rejects.
    assert!(!r.contains(Point::new(10, 4)), "bx is exclusive");
    assert!(!r.contains(Point::new(9, 5)), "by is exclusive");
    assert!(!r.contains(Point::new(-1, 0)), "negative x rejects");

    // contains_rect is the half-open analogue: inner ⊆ outer iff
    // inner.ax >= outer.ax && inner.bx <= outer.bx etc.
    let inner = Rect::new(2, 1, 8, 4);
    assert!(r.contains_rect(inner));

    let exact = r;
    assert!(r.contains_rect(exact));

    let too_wide = Rect::new(0, 0, 11, 5);
    assert!(!r.contains_rect(too_wide));
}

#[test]
fn test_geometry_align_offset_all_four_modes() {
    // align_offset(container_size, child_size, mode) returns the
    // offset within `container` at which to position `child` for a
    // given alignment mode. Modes per FASM:
    //   0 = start  → 0
    //   1 = center → slack / 2
    //   2 = end    → slack
    //   3 = fill   → 0
    // When child >= container the slack is non-positive and the
    // function returns 0 regardless of mode.
    assert_eq!(align_offset(20, 10, 0), 0); // start
    assert_eq!(align_offset(20, 10, 1), 5); // center: slack=10, /2=5
    assert_eq!(align_offset(20, 10, 2), 10); // end:    slack=10
    assert_eq!(align_offset(20, 10, 3), 0); // fill

    // Center with odd slack rounds down (10/2 == 5, 11/2 == 5).
    assert_eq!(align_offset(21, 10, 1), 5);

    // Child equal to container — no slack, returns 0 in every mode.
    assert_eq!(align_offset(10, 10, 0), 0);
    assert_eq!(align_offset(10, 10, 1), 0);
    assert_eq!(align_offset(10, 10, 2), 0);

    // Child larger than container — also returns 0.
    assert_eq!(align_offset(5, 10, 1), 0);
    assert_eq!(align_offset(5, 10, 2), 0);
}

// ============================================================================
// Section 3: Widget Tree Compose (2 tests)
//
// Tests of the actual widget tree composition: we construct widgets,
// compose them, and verify byte-level rendering by passing a TestSink
// through the trait methods. This is the spirit of AAP §0.3.1.2's
// "rendered-frame byte comparison".
//
// Note: the missing `Panel` widget (Issue 2 — deferred per
// `widgets/mod.rs`) means we cannot test `Panel + Label` composition
// directly. Instead, we test that the existing widgets we DO have
// (TuiBackground + TuiVLine/TuiHLine) round-trip through our TestSink
// without panicking and produce sensible field state.
// ============================================================================

#[test]
fn test_widget_tree_background_construction_and_field_invariants() {
    // Construct a TuiBackground via new_ii (integer width × integer
    // height, fillchar = U+0020 SPACE, white-on-blue colors).
    let colors = ColorPair::new(7, 4); // fg=7 (white), bg=4 (blue)
    let bg = TuiBackground::new_ii(10, 5, b' ' as u32, colors)
        .expect("new_ii must succeed for typical dimensions");

    // The Arc<Self> return type gives us a shareable, reference-
    // counted handle. This is the same pattern FASM `tui_background$
    // new_ii` uses to allocate a heap slot and return a pointer.
    assert_eq!(Arc::strong_count(&bg), 1);

    // Verify the public accessors return what we passed in.
    assert_eq!(bg.fillchar(), b' ' as u32);
    assert_eq!(bg.colors(), colors);

    // A freshly constructed widget has its WidgetState seeded with
    // FASM `tui_object$init_defaults` semantics: visible=true,
    // include_in_layout=true, absolute_x=-1, absolute_y=-1.
    let state = bg.state();
    assert!(state.visible);
    assert!(state.include_in_layout);
    assert_eq!(state.absolute_x, -1);
    assert_eq!(state.absolute_y, -1);

    // Width and height fields reflect the constructor arguments.
    assert_eq!(state.width, 10);
    assert_eq!(state.height, 5);
    // Width/height percent are None for the integer constructor.
    assert!(state.width_percent.is_none());
    assert!(state.height_percent.is_none());
}

#[test]
fn test_widget_tree_renderer_round_trip_through_test_sink() {
    // Verify that an Arc<TuiBackground> can be cloned to Arc<dyn
    // Widget> without unsafe trait-object casts (this is the standard
    // composition pattern other widgets use to embed children). The
    // unsized dyn Widget coercion happens automatically in Rust.
    let colors = ColorPair::new(15, 0);
    let bg = TuiBackground::new_ii(4, 2, b'#' as u32, colors).expect("new_ii must succeed");

    // Coerce to Arc<dyn Widget> — this exercises the widget trait
    // object as it would be stored in `WidgetState.children`.
    let widget: Arc<dyn Widget> = bg.clone();
    let _state_ref = widget.state();

    // Now exercise our TestSink — ansi_output / flush should both
    // succeed and accumulate bytes / increment flush count.
    let mut sink = TestSink::new();

    // Direct ansi_output of a known byte sequence.
    sink.ansi_output(ansi::CURSOR_HOME).unwrap();
    sink.ansi_output(b"hello").unwrap();
    sink.flush().unwrap();

    // Verify byte capture: CURSOR_HOME (3 bytes) + "hello" (5 bytes) = 8 bytes.
    assert_eq!(sink.out.len(), 8);
    assert_eq!(&sink.out[0..3], ansi::CURSOR_HOME);
    assert_eq!(&sink.out[3..], b"hello");
    assert_eq!(sink.flush_count, 1);

    // Use the trait default `move_cursor` path — should emit
    // `ESC[2;3H` (move to row=2 col=3) on first call, and elide
    // a redundant move on second call to the same coordinates.
    let mut sink2 = TestSink::new();
    sink2.move_cursor(2, 3).unwrap();
    let len_after_first = sink2.out.len();
    assert!(len_after_first > 0, "first move_cursor must emit bytes");
    // ANSI cursor move is `ESC[<row>;<col>H` — verify the suffix.
    assert!(sink2.out.starts_with(b"\x1b["));
    assert!(sink2.out.ends_with(b"H"));
    // Both row=2 and col=3 must appear as ASCII digits.
    let s = std::str::from_utf8(&sink2.out).unwrap();
    assert!(s.contains('2'));
    assert!(s.contains('3'));

    // Second call with identical coordinates is elided (no bytes).
    sink2.move_cursor(2, 3).unwrap();
    assert_eq!(
        sink2.out.len(),
        len_after_first,
        "redundant move_cursor must be elided"
    );
}

// ============================================================================
// Section 4: ACS Lines (1 test)
//
// Verify that VLINE_CHAR and HLINE_CHAR have the exact Unicode
// codepoints specified by FASM `tui_lines.inc` (`0x2502` for vertical,
// `0x2500` for horizontal) and that the line-factory constructors
// produce TuiBackground widgets pre-filled with these codepoints.
// ============================================================================

#[test]
fn test_acs_line_characters_unicode_codepoints_and_factory_pre_fill() {
    // Per FASM `tui_lines.inc` lines 40 and 84, vertical and
    // horizontal line widgets are pre-filled with U+2502 (BOX
    // DRAWINGS LIGHT VERTICAL `│`) and U+2500 (BOX DRAWINGS LIGHT
    // HORIZONTAL `─`) respectively. The constants must match
    // byte-for-byte.
    assert_eq!(VLINE_CHAR, 0x2502);
    assert_eq!(HLINE_CHAR, 0x2500);

    // The FASM constants are also valid Rust char literals:
    assert_eq!(char::from_u32(VLINE_CHAR).unwrap(), '│');
    assert_eq!(char::from_u32(HLINE_CHAR).unwrap(), '─');

    // VLine factory: width=1 cell, height=N (caller-supplied),
    // fillchar=VLINE_CHAR.
    let colors = ColorPair::new(7, 0);
    let vline = TuiVLine::new_i(20, colors).expect("new_i must succeed");
    assert_eq!(vline.fillchar(), VLINE_CHAR);
    assert_eq!(vline.colors(), colors);
    assert_eq!(vline.state().width, 1);
    assert_eq!(vline.state().height, 20);

    // HLine factory: width=N (caller-supplied), height=1 cell,
    // fillchar=HLINE_CHAR.
    let hline = TuiHLine::new_i(40, colors).expect("new_i must succeed");
    assert_eq!(hline.fillchar(), HLINE_CHAR);
    assert_eq!(hline.colors(), colors);
    assert_eq!(hline.state().width, 40);
    assert_eq!(hline.state().height, 1);

    // ACS_LINECHARS configuration default — when this is true the
    // renderer translates VLINE_CHAR / HLINE_CHAR to VT100 ACS
    // glyphs `x` / `q` at emit time. Per FASM `ht_defaults.inc`
    // the default is `1` (true), so it must remain true here.
    // Use a compile-time const assertion so a regression is caught at
    // compile time instead of test time. Clippy's
    // `assertions_on_constants` lint recommends this pattern when
    // asserting on a `const` value.
    const _: () = assert!(config::ACS_LINECHARS, "ACS_LINECHARS default must be true");
}

// ============================================================================
// Section 5: Alt-Screen Mode (2 tests)
//
// Verify that:
// 1. The TERMINAL_ALTERNATESCREEN and TUI_SSH_ALTERNATESCREEN config
//    flags are both `true` by default per FASM `ht_defaults.inc`.
// 2. The byte sequences for entering and exiting the alternate-screen
//    mode are exactly `ESC[?1049h` and `ESC[?1049l`.
//
// The `RawTerminal::enter()` syscall path is NOT exercised here
// because that requires a real TTY and conflicts with the
// `test_raw_terminal_roundtrip` test in `ffi_boundary.rs`. We instead
// verify the constants the syscall path would emit.
// ============================================================================

#[test]
fn test_alt_screen_config_defaults_match_fasm() {
    // FASM `ht_defaults.inc` line ~ 270 defines:
    //   terminal_alternatescreen = 1
    //   tui_ssh_alternatescreen  = 1
    // Both must be `true` in Rust to preserve identical default
    // behavior — sshtalk and other TUI applications expect their
    // session to start in the alternate buffer.
    //
    // Use compile-time const assertions per Clippy's
    // `assertions_on_constants` recommendation: this pattern catches
    // a regression at compile time rather than test time.
    const _: () = assert!(
        config::TERMINAL_ALTERNATESCREEN,
        "TERMINAL_ALTERNATESCREEN default must be true (FASM parity)"
    );
    const _: () = assert!(
        config::TUI_SSH_ALTERNATESCREEN,
        "TUI_SSH_ALTERNATESCREEN default must be true (FASM parity)"
    );
}

#[test]
fn test_alt_screen_enter_exit_byte_sequences_through_test_sink() {
    // Simulate the byte stream a `RawTerminal::enter` / `Drop` pair
    // would emit by writing the alt-screen-enter sequence on enter
    // and the alt-screen-exit sequence on drop. The TestSink captures
    // these bytes verbatim, allowing exact assertion.
    let mut sink = TestSink::new();

    // Enter sequence: the FASM `tui_terminal.inc` lines 308–316
    // sequence is alt-screen-enter → hide-cursor → clear-screen →
    // cursor-home. We replicate that sequence here.
    sink.ansi_output(ansi::ALT_SCREEN_ENTER).unwrap();
    sink.ansi_output(ansi::HIDE_CURSOR).unwrap();
    sink.ansi_output(ansi::CLEAR_SCREEN).unwrap();
    sink.ansi_output(ansi::CURSOR_HOME).unwrap();

    // Reverse on drop / exit:
    sink.ansi_output(ansi::SHOW_CURSOR).unwrap();
    sink.ansi_output(ansi::ALT_SCREEN_EXIT).unwrap();

    // Now verify the captured byte stream contains both bracketing
    // sequences in the expected order.
    let expected = {
        let mut v = Vec::new();
        v.extend_from_slice(ansi::ALT_SCREEN_ENTER);
        v.extend_from_slice(ansi::HIDE_CURSOR);
        v.extend_from_slice(ansi::CLEAR_SCREEN);
        v.extend_from_slice(ansi::CURSOR_HOME);
        v.extend_from_slice(ansi::SHOW_CURSOR);
        v.extend_from_slice(ansi::ALT_SCREEN_EXIT);
        v
    };
    assert_eq!(sink.out, expected);

    // Verify the alt-screen-enter byte sequence appears at the start
    // and alt-screen-exit appears at the end — bracketing the
    // session as the FASM RawTerminal does.
    assert!(sink.out.starts_with(ansi::ALT_SCREEN_ENTER));
    assert!(sink.out.ends_with(ansi::ALT_SCREEN_EXIT));
}

// ============================================================================
// Section 6: Raw Terminal (1 test)
//
// Verify that the public types and associated functions of the
// `terminal` module compile and produce the expected default values
// without invoking the privileged singleton path. Specifically:
//   - WindowSize derives Copy + PartialEq + Eq
//   - RawTerminal::exit_pending() is an associated function (not method)
//     and returns false in a fresh process state.
// ============================================================================

#[test]
fn test_raw_terminal_window_size_and_exit_pending() {
    // WindowSize struct API: rows + cols u16 fields, derives Copy +
    // PartialEq + Eq + Hash (the Hash impl is required for some
    // future scheduling code — verified at compile time below by
    // putting WindowSize in a HashSet).
    let ws1 = WindowSize { rows: 24, cols: 80 };
    let ws2 = WindowSize { rows: 24, cols: 80 };
    assert_eq!(ws1, ws2, "WindowSize must derive PartialEq");

    let ws3 = WindowSize { rows: 25, cols: 80 };
    assert_ne!(ws1, ws3);

    // Copy semantics: ws1 must remain valid after a copy.
    let ws_copy = ws1;
    assert_eq!(ws1.rows, 24);
    assert_eq!(ws1.cols, 80);
    assert_eq!(ws_copy.rows, 24);
    assert_eq!(ws_copy.cols, 80);

    // exit_pending is an *associated function* (no `&self`); per
    // FASM `tui_terminal.inc` the EXIT_PENDING atomic flag is global
    // and the accessor is a static query rather than a per-instance
    // method.
    //
    // In a fresh process this flag has not been set by any signal
    // handler, so it must read `false`. We do not call enter() here
    // (that would conflict with `ffi_boundary::test_raw_terminal_
    // roundtrip`), but exit_pending is callable independently of
    // any `RawTerminal` instance.
    assert!(
        !RawTerminal::exit_pending(),
        "EXIT_PENDING must default to false in a fresh process"
    );
}

// ============================================================================
// Section 7: Background Widget — write-through + accessor invariants
// ============================================================================

#[test]
fn test_background_widget_setters_round_trip_field_state() {
    // Construct a TuiBackground and exercise the write-side accessors
    // by going through the Arc<Self> directly. We verify that the
    // get_*() accessors return the same values seen by the field-
    // level reads on `state()`.
    let colors = ColorPair::new(15, 0);
    let bg = TuiBackground::new_ii(8, 4, b'.' as u32, colors).expect("new_ii must succeed");

    // Initial accessor reads must reflect the constructor arguments.
    assert_eq!(bg.fillchar(), b'.' as u32);
    assert_eq!(bg.colors(), colors);

    // The state-side absolute_x/y sentinels are the FASM "not yet
    // positioned" markers — must be -1 until layout assigns them.
    assert_eq!(bg.state().absolute_x, -1);
    assert_eq!(bg.state().absolute_y, -1);

    // Per the FASM `tui_object$init_defaults` line 192 contract,
    // the initial bounds rect is the default (zeroed) Rect.
    assert_eq!(bg.state().bounds, Rect::default());

    // Verify the trait-default `Widget::cleanup` path runs without
    // panicking on a freshly-constructed widget. We need to obtain
    // a unique reference, which means the Arc must have refcount=1.
    let mut owned = Arc::try_unwrap(bg).unwrap_or_else(|_| {
        panic!("Arc::try_unwrap must succeed when refcount==1");
    });
    owned.cleanup();
    // After cleanup the children/bastards lists are clear and the
    // text/attributes buffers are zeroed (only their capacity
    // potentially survives via the FASM never-shrink discipline).
    assert!(owned.state().display_name.is_empty());
}

// ============================================================================
// Section 8: TuiError variant Display + construction (1 test)
//
// Verify that all three `TuiError` variants (Termios, Winsize, Render)
// can be constructed from `io::Error` sources and produce the
// thiserror-defined Display output. `TuiError` does not derive
// `PartialEq`, so we use pattern-matching to discriminate variants.
// ============================================================================

#[test]
fn test_tui_error_all_variants_display_and_construction() {
    use std::io;

    // Termios variant: wraps an io::Error from `tcgetattr` / `cfmakeraw`
    // / `tcsetattr` per FASM `tui_terminal.inc`.
    let termios_io = io::Error::new(io::ErrorKind::AlreadyExists, "double-enter");
    let termios_err = TuiError::Termios(termios_io);
    let rendered = termios_err.to_string();
    assert!(
        rendered.starts_with("terminal raw mode failed:"),
        "Termios Display prefix mismatch: {rendered:?}"
    );
    assert!(
        rendered.contains("double-enter"),
        "Termios source message missing: {rendered:?}"
    );
    match termios_err {
        TuiError::Termios(_) => {}
        other => panic!("expected Termios, got {other:?}"),
    }

    // Winsize variant: wraps an io::Error from `ioctl(TIOCGWINSZ)`.
    let winsize_io = io::Error::other("winsize ioctl failed");
    let winsize_err = TuiError::Winsize(winsize_io);
    let rendered = winsize_err.to_string();
    assert!(
        rendered.starts_with("terminal winsize query failed:"),
        "Winsize Display prefix mismatch: {rendered:?}"
    );
    assert!(rendered.contains("winsize ioctl failed"));
    match winsize_err {
        TuiError::Winsize(_) => {}
        other => panic!("expected Winsize, got {other:?}"),
    }

    // Render variant: wraps an io::Error from a renderer's underlying
    // sink (terminal output stream / SSH channel write).
    let render_io = io::Error::new(io::ErrorKind::BrokenPipe, "sink unavailable");
    let render_err = TuiError::Render(render_io);
    let rendered = render_err.to_string();
    assert!(
        rendered.starts_with("render failure:"),
        "Render Display prefix mismatch: {rendered:?}"
    );
    assert!(rendered.contains("sink unavailable"));
    match render_err {
        TuiError::Render(_) => {}
        other => panic!("expected Render, got {other:?}"),
    }

    // The `std::error::Error` trait is implemented (via thiserror
    // derive) — each variant has an underlying io::Error source.
    use std::error::Error as StdError;
    let with_source = TuiError::Termios(io::Error::new(io::ErrorKind::PermissionDenied, "oops"));
    assert!(
        with_source.source().is_some(),
        "TuiError::Termios must carry its io::Error as source"
    );
}
