"""KAT runner for HMAC-DRBG (``hmac_drbg.inc`` -- the ``hmac_drbg$new`` /
``hmac_drbg$generate`` / ``hmac_drbg$generate_additional`` /
``hmac_drbg$destroy`` family) vs NIST SP 800-90A CAVP HMAC_DRBG (SHA-256)
inputs.

Each vector in ``tests/vectors/hmac_drbg.json`` is fanned out into one
parametrized case that subprocess-invokes the harness as
``kat_hmac_drbg <entropy_hex> <nonce_hex> <personalization_hex>
<additional_hex> <requested_bytes>`` and asserts its lowercase-hex stdout
(the generated bytes) against ``expected_hex``. The harness drives
``hmac_drbg$new`` -> ``hmac_drbg$generate`` (or
``hmac_drbg$generate_additional`` when ``additional_hex`` is non-empty) ->
``hmac_drbg$destroy``, reaching 100% of the DRBG's public API (AAP 0.3.1).

HMAC-DRBG would be nondeterministic in production, but the NIST vectors fix
entropy/nonce/personalization so the output is fully reproducible (AAP 0.10.3).
The runner treats it like any other deterministic KAT, with one extra branch:
the ``negative_generate_after_destroy`` vector (flagged ``expect_error``)
destroys the context then attempts generate, which MUST exit nonzero -- so that
case asserts on the return code, not the hex.

Pure standard library + pytest, no mocks (HMAC-DRBG is a pure function of its
fixed entropy inputs); this module only loads vectors, drives the subprocess,
and compares hex (or the exit status for the destroy negative).
"""

import pytest

from ._harness import load_vectors, run_kat, assert_hex_equal, param_id

# Load the committed NIST SP 800-90A HMAC-DRBG KAT array once at import time; a
# missing or malformed fixture surfaces now, not as an empty parametrize.
VECTORS = load_vectors("hmac_drbg")

# Node ids are "<category>-<id>" (HMAC-DRBG has no extra variant dimension --
# SHA-256 is the fixed DRBG hash), so ``-k "happy_path"`` / ``-k "negative"`` /
# ``-k "edge_case"`` select coherent subsets.
IDS = [param_id(vector) for vector in VECTORS]


def _args(vector):
    """Build ``kat_hmac_drbg`` argv for a vector, matching ``kat_hmac_drbg.c``.

    Fixed order ``<entropy_hex> <nonce_hex> <personalization_hex>
    <additional_hex> <requested_bytes>``. Empty optional fields are passed as
    ``""``; ``personalization_hex`` / ``additional_hex`` use defensive
    ``.get`` defaults so a vector that omits them never raises ``KeyError``.
    """
    return [
        vector["entropy_hex"],
        vector["nonce_hex"],
        vector.get("personalization_hex", ""),
        vector.get("additional_hex", ""),
        str(vector["requested_bytes"]),
    ]


@pytest.mark.parametrize("vector", VECTORS, ids=IDS)
def test_kat(vector):
    """Run one HMAC-DRBG KAT vector through ``kat_hmac_drbg``; assert output.

    Three-way dispatch (the ``expect_error`` branch is unique to this module):

    1. ``expect_error`` (generate-after-destroy) -> the harness MUST exit
       nonzero; assert on the return code and do NOT compare hex.
    2. ``expect_mismatch`` -> the harness must exit 0 but its output must NOT
       reproduce ``expected_hex`` (branch kept for cross-module uniformity).
    3. Every other vector -> the harness must exit 0 and emit exactly
       ``expected_hex`` (R8 full-coverage, R9 zero-tolerance).
    """
    rc, out = run_kat("kat_hmac_drbg", vector, args=_args(vector))
    if vector.get("expect_error"):
        assert rc != 0, (
            f"{vector['id']}: generate-after-destroy must exit nonzero"
        )
        return
    assert rc == 0, f"kat_hmac_drbg exited {rc} for {vector['id']}"
    if vector.get("expect_mismatch"):
        assert out.strip().lower() != vector["expected_hex"], (
            f"{vector['id']}: unexpectedly matched expected_hex"
        )
    else:
        assert_hex_equal(out, vector["expected_hex"])
