"""KAT runner for HMAC-DRBG (``hmac_drbg.inc`` -- the ``hmac_drbg$new`` /
``hmac_drbg$generate`` / ``hmac_drbg$generate_additional`` /
``hmac_drbg$destroy`` family) vs NIST SP 800-90A CAVP HMAC_DRBG (SHA-256)
inputs.

Each vector in ``tests/vectors/hmac_drbg.json`` is fanned out into one
parametrized case that subprocess-invokes the harness as
``kat_hmac_drbg <entropy_hex> <nonce_hex> <personalization_hex>
<additional_hex> <requested_bytes>`` and asserts its lowercase-hex stdout
(the generated bytes) against ``expected_hex``. The harness drives
``hmac_drbg$new`` -> ``hmac_drbg$generate`` (or
``hmac_drbg$generate_additional`` when ``additional_hex`` is non-empty) ->
``hmac_drbg$destroy``, reaching 100% of the DRBG's public API (AAP 0.3.1).

ACCEPTED DEVIATION (HMAC-DRBG): HeavyThing's ``hmac_drbg$new`` omits the final
V = HMAC(K, V) update after the second K update, so its generated bytes deviate
from the published NIST SP 800-90A CAVP ReturnedBits. Per AAP 0.10.2 (honor
intent for primitives that exist; document deviations rather than fabricate
standards results) this is a formally accepted deviation: the CAVP
entropy/nonce/personalization INPUTS are used verbatim, but the committed
``expected_hex`` values are the HeavyThing-ACTUAL deterministic OUTPUTS of this
implementation. ``tests/vectors/hmac_drbg.json`` records the matching
``source`` attribution and the "Accepted Deviations Registry" in
``tests/README.md`` carries the full rationale.

HMAC-DRBG would be nondeterministic in production, but fixing
entropy/nonce/personalization makes the output fully reproducible (AAP 0.10.3).
The runner treats it like any other deterministic KAT, with one extra branch:
the ``negative_generate_after_destroy`` vector (flagged ``expect_error``)
exercises the generate-after-destroy contract -- the harness destroys the
context and then refuses to reuse it, failing cleanly with a POSITIVE nonzero
exit and empty stdout (it does NOT crash). That case asserts ``rc > 0`` and an
empty stdout, explicitly rejecting signal/SIGSEGV termination (rc < 0).

Pure standard library + pytest, no mocks (HMAC-DRBG is a pure function of its
fixed entropy inputs); this module only loads vectors, drives the subprocess,
and compares hex (or the exit status for the destroy negative).
"""

import pytest

from ._harness import load_vectors, run_kat, assert_hex_equal, param_id

# Load the committed NIST SP 800-90A HMAC-DRBG KAT array once at import time; a
# missing or malformed fixture surfaces now, not as an empty parametrize.
VECTORS = load_vectors("hmac_drbg")

# Node ids are "<category>-<id>" (HMAC-DRBG has no extra variant dimension --
# SHA-256 is the fixed DRBG hash), so ``-k "happy_path"`` / ``-k "negative"`` /
# ``-k "edge_case"`` select coherent subsets.
IDS = [param_id(vector) for vector in VECTORS]


def _args(vector):
    """Build ``kat_hmac_drbg`` argv for a vector, matching ``kat_hmac_drbg.c``.

    Fixed order ``<entropy_hex> <nonce_hex> <personalization_hex>
    <additional_hex> <requested_bytes>``. Empty optional fields are passed as
    ``""``; ``personalization_hex`` / ``additional_hex`` use defensive
    ``.get`` defaults so a vector that omits them never raises ``KeyError``.
    """
    return [
        vector["entropy_hex"],
        vector["nonce_hex"],
        vector.get("personalization_hex", ""),
        vector.get("additional_hex", ""),
        str(vector["requested_bytes"]),
    ]


@pytest.mark.parametrize("vector", VECTORS, ids=IDS)
def test_kat(vector):
    """Run one HMAC-DRBG KAT vector through ``kat_hmac_drbg``; assert output.

    Three-way dispatch (the ``expect_error`` branch is unique to this module):

    1. ``expect_error`` (generate-after-destroy) -> the harness MUST fail
       cleanly with a POSITIVE nonzero exit (``rc > 0``) and empty stdout. A
       negative rc is signal termination (e.g. -11 SIGSEGV from a
       use-after-free) and is explicitly REJECTED so a crash can never pass.
       Asserts the exit status, not the hex.
    2. ``expect_mismatch`` -> the harness must exit 0 but its output must NOT
       reproduce ``expected_hex`` (branch kept for cross-module uniformity).
    3. Every other vector -> the harness must exit 0 and emit exactly
       ``expected_hex`` (R8 full-coverage, R9 zero-tolerance).
    """
    rc, out = run_kat("kat_hmac_drbg", vector, args=_args(vector))
    if vector.get("expect_error"):
        # Demand a clean, deterministic failure: a POSITIVE exit status. A
        # negative rc is signal/crash termination (e.g. -11 SIGSEGV) and MUST
        # NOT pass -- accepting it would mask real memory corruption. A cleanly
        # failing harness also writes nothing to stdout.
        assert rc > 0, (
            f"{vector['id']}: generate-after-destroy must fail cleanly with a "
            f"positive nonzero exit; got rc={rc} "
            f"(rc < 0 is signal/crash termination and is rejected)"
        )
        assert out.strip() == "", (
            f"{vector['id']}: a cleanly-failing harness must emit empty "
            f"stdout, got {out.strip()!r}"
        )
        return
    assert rc == 0, f"kat_hmac_drbg exited {rc} for {vector['id']}"
    if vector.get("expect_mismatch"):
        assert out.strip().lower() != vector["expected_hex"], (
            f"{vector['id']}: unexpectedly matched expected_hex"
        )
    else:
        assert_hex_equal(out, vector["expected_hex"])
