// ------------------------------------------------------------------------
// HeavyThing Rust translation — AES-128-CBC throughput benchmark
// Copyright © 2015 2 Ton Digital, Jeff Marrison <jeff@2ton.com.au>
// Homepage: https://2ton.com.au/
//
// This file is part of the HeavyThing Rust translation.
//
// HeavyThing is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// HeavyThing is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with the HeavyThing library. If not, see <https://www.gnu.org/licenses/>.
// ------------------------------------------------------------------------
//
// aes_cbc.rs: Criterion benchmark for AES-128-CBC encryption / decryption
//             throughput.
//
// Source: exercises Rust code at `crates/heavything/src/crypto/aes.rs`
// that replaces `aes.inc` (1,423 lines: AES-NI hardware path + Wei Dai
// public-domain software fallback). The Rust port delegates to the
// `aes` + `cbc` RustCrypto crates (constant-time, FIPS 197-compliant)
// because `ring` does not expose raw AES-CBC (AAP §0.7.2.2).
//
// AAP §0.8.5 mandates this benchmark as part of the Gate 3 deliverable
// (`BENCHMARK_REPORT.md`): the Rust implementation MUST sustain AES-128-CBC
// throughput within 3× of the assembly baseline (AAP §0.8.1). The bench
// produces raw measurements only; the assembly-vs-Rust comparison table
// is generated by a sibling agent that runs the assembly binaries (see
// AAP §0.8.5 baseline save/compare workflow).
//
// Input sizes (per AAP §0.8.5 protocol harmonization):
//   * 64 B    — single AES block × 4 (matches the smallest TLS record header)
//   * 1 KiB   — typical HTTP request / SSH packet boundary
//   * 16 KiB  — TLS 1.2 maximum record size (RFC 5246 §6.2.1)
//   * 256 KiB — large message / static asset chunk
//   * 1 MiB   — bulk transfer regime (AES-NI saturation point)
//
// Runs:
//   cargo bench --bench aes_cbc -p heavything
//
// Baseline save/compare:
//   cargo bench --bench aes_cbc -p heavything -- --save-baseline rust_v1
//   cargo bench --bench aes_cbc -p heavything -- --baseline rust_v1
//
// CRITICAL CONSTRAINT (per AAP §0.6.3.3 / §0.8.7): the workspace pins
// `criterion = "0.5"` WITHOUT the `async_tokio` feature. AES is purely
// CPU-bound so no tokio bridge is required here — the bench is fully
// synchronous (`b.iter(|| ...)`) and never awaits.

#![forbid(unsafe_code)]
#![allow(clippy::unwrap_used)]
#![allow(clippy::expect_used)]

use std::time::Duration;

use criterion::{
    black_box, criterion_group, criterion_main, BenchmarkId, Criterion, Throughput,
};

use heavything::crypto::aes::{
    aes128_cbc_new_decrypt, aes128_cbc_new_encrypt, AES128_KEY_SIZE, BLOCK_SIZE,
};

// ============================================================================
// Module-level constants — deterministic key / IV / size set.
// ============================================================================

/// AES-128 input sizes covered by the benchmark.
///
/// Every size is a multiple of 16 (the AES block size) so that the
/// CBC `encrypt_blocks` / `decrypt_blocks` API contract (input length
/// MUST be a multiple of `BLOCK_SIZE`) is satisfied without padding.
///
/// Per AAP §0.8.5 the bench surfaces both small-record and bulk-transfer
/// throughput regimes:
///
/// * `64`         — sub-page record (TLS heartbeat, SSH `KEX_INIT`).
/// * `1024`       — typical HTTP request / SSH channel-data packet.
/// * `16384`      — TLS 1.2 maximum record (RFC 5246 §6.2.1).
/// * `262_144`    — large static-asset chunk.
/// * `1_048_576`  — bulk-transfer regime; AES-NI saturation point.
const INPUT_SIZES: &[usize] = &[64, 1024, 16_384, 262_144, 1_048_576];

/// Fixed AES-128 key — `b"heavything-bench-aes-key-128bits!"[..16]`.
///
/// Hardcoded (not random) so that runs are reproducible across CI and
/// local dev, and so that criterion's iteration-to-iteration measurements
/// are not perturbed by per-iteration key derivation cost. Byte-identity
/// of input keys across runs is the standard convention for throughput
/// micro-benchmarks (key-schedule cost is amortized to zero by the
/// `b.iter()` harness).
const KEY: [u8; AES128_KEY_SIZE] = *b"heavything-bench";

/// Fixed AES-CBC initial value (IV).
///
/// The IV is per-message in production protocols (TLS 1.2 GenericBlockCipher
/// uses an explicit IV per record; SSH derives a fresh IV via key
/// exchange). For the bench, a deterministic IV is sufficient because the
/// IV's role is to randomize the first block — its value does not affect
/// throughput, only the ciphertext output. Choosing `0xa5` repeated mirrors
/// the FASM `aes$test` pattern (`aes.inc` §test_vectors).
const IV: [u8; BLOCK_SIZE] = [0xa5; BLOCK_SIZE];

// ============================================================================
// Helper — populate a vector with deterministic non-zero plaintext.
// ============================================================================

/// Build a `Vec<u8>` of length `size` filled with a deterministic
/// non-trivial pattern.
///
/// A pure-zero buffer would let CPU branch-predictors / data-prefetchers
/// optimize the inner loop in unrealistic ways, biasing the measurement
/// downward. The `(i * 31 + 7) & 0xff` pattern is the same one used by
/// `tests/net_integration.rs` Section 6 (TCP echo) and matches the
/// FASM `aes_test_*` plaintext generation convention.
fn make_plaintext(size: usize) -> Vec<u8> {
    debug_assert_eq!(
        size % BLOCK_SIZE,
        0,
        "AES-CBC bench plaintext length MUST be a multiple of {} bytes",
        BLOCK_SIZE
    );
    let mut buf = vec![0u8; size];
    for (i, b) in buf.iter_mut().enumerate() {
        *b = ((i.wrapping_mul(31).wrapping_add(7)) & 0xff) as u8;
    }
    buf
}

// ============================================================================
// Benchmark — AES-128-CBC encryption throughput.
// ============================================================================

/// Measure AES-128-CBC encryption throughput at every input size in
/// [`INPUT_SIZES`].
///
/// Each iteration:
///   1. Constructs a fresh `Aes128Cbc` encryptor (key-schedule + IV setup
///      via `cbc::Encryptor::<Aes128>::new`). The constructor cost is
///      included in the iteration so the headline number is
///      end-to-end "encrypt N bytes from cold" — matching what the
///      FASM `aes$encrypt_init + aes$encrypt` flow measures.
///   2. Calls `encrypt_blocks` on a mutable copy of the plaintext.
///   3. Discards the ciphertext via [`black_box`] to prevent the
///      compiler optimizing away the encryption step.
///
/// Criterion is configured with `Throughput::Bytes(size)` so the
/// reported value is in bytes/second (the headline metric for
/// crypto bandwidth).
///
/// Sample size is the criterion default (100) for sizes ≤ 16 KiB, and
/// reduced to 50 for the two largest sizes — those iterations are slow
/// enough that the default would target an unreasonable wall-clock
/// duration per benchmark. The reduction is the same accommodation
/// applied in `bench_http_concurrent` (`http_roundtrip.rs`).
fn bench_aes128_cbc_encrypt(c: &mut Criterion) {
    let mut group = c.benchmark_group("aes_cbc/encrypt/aes128");
    group.warm_up_time(Duration::from_secs(3));
    group.measurement_time(Duration::from_secs(5));

    for &size in INPUT_SIZES {
        // Pre-generate the plaintext outside the iter loop so allocation
        // cost is amortized to zero. Per-iteration we clone into a
        // working buffer (clone cost is included in the measurement,
        // matching the FASM `aes$encrypt`'s in-place-on-caller-buffer
        // semantic where the caller copies from a source buffer).
        let plaintext = make_plaintext(size);

        // Sample size: 100 default for small inputs, 50 for ≥256 KiB to
        // keep the per-bench wall-clock reasonable.
        if size >= 262_144 {
            group.sample_size(50);
        } else {
            group.sample_size(100);
        }

        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(
            BenchmarkId::from_parameter(size),
            &plaintext,
            |b, plaintext| {
                b.iter(|| {
                    let mut buf = plaintext.clone();
                    let mut enc = aes128_cbc_new_encrypt(&KEY, &IV)
                        .expect("aes128_cbc_new_encrypt should succeed for valid key + IV");
                    enc.encrypt_blocks(black_box(&mut buf))
                        .expect("AES-128-CBC encrypt_blocks should succeed");
                    // `black_box` consumes the ciphertext so the compiler
                    // cannot eliminate the round-key writes or the
                    // encryption inner loop.
                    black_box(buf);
                });
            },
        );
    }

    group.finish();
}

// ============================================================================
// Benchmark — AES-128-CBC decryption throughput.
// ============================================================================

/// Measure AES-128-CBC decryption throughput at every input size in
/// [`INPUT_SIZES`].
///
/// Mirrors [`bench_aes128_cbc_encrypt`] but exercises the
/// [`cbc::Decryptor::<Aes128>`] code path via
/// [`heavything::crypto::aes::aes128_cbc_new_decrypt`]. The decryption
/// inverse-key-schedule cost is included per-iteration for the same
/// "from cold" measurement convention.
///
/// In practice CBC decryption is fully parallelizable across blocks
/// (every block depends only on the previous ciphertext block, not the
/// previous plaintext), so AES-NI hardware achieves higher decryption
/// throughput than encryption. The bench reports both sides so the
/// asymmetry is visible in `BENCHMARK_REPORT.md`.
fn bench_aes128_cbc_decrypt(c: &mut Criterion) {
    let mut group = c.benchmark_group("aes_cbc/decrypt/aes128");
    group.warm_up_time(Duration::from_secs(3));
    group.measurement_time(Duration::from_secs(5));

    for &size in INPUT_SIZES {
        // Construct the ciphertext once via a one-shot encrypt path.
        // The decryption iter loop does NOT include the encryption
        // setup in its measurement — only the decryption work itself,
        // which is the property under measurement.
        let plaintext = make_plaintext(size);
        let mut enc = aes128_cbc_new_encrypt(&KEY, &IV)
            .expect("aes128_cbc_new_encrypt setup for decrypt-bench fixture");
        let mut ciphertext = plaintext;
        enc.encrypt_blocks(&mut ciphertext)
            .expect("encrypt_blocks setup for decrypt-bench fixture");

        if size >= 262_144 {
            group.sample_size(50);
        } else {
            group.sample_size(100);
        }

        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(
            BenchmarkId::from_parameter(size),
            &ciphertext,
            |b, ciphertext| {
                b.iter(|| {
                    let mut buf = ciphertext.clone();
                    let mut dec = aes128_cbc_new_decrypt(&KEY, &IV)
                        .expect("aes128_cbc_new_decrypt should succeed for valid key + IV");
                    dec.decrypt_blocks(black_box(&mut buf))
                        .expect("AES-128-CBC decrypt_blocks should succeed");
                    black_box(buf);
                });
            },
        );
    }

    group.finish();
}

// ============================================================================
// Criterion entry-points.
//
// `criterion_group!` aggregates the encrypt + decrypt benchmark
// functions. `criterion_main!` synthesises the `fn main()` entry that
// `cargo bench --bench aes_cbc` invokes (the `[[bench]]` entry in
// `crates/heavything/Cargo.toml` sets `harness = false`, deferring to
// criterion's harness instead of the default libtest harness).
// ============================================================================

criterion_group!(benches, bench_aes128_cbc_encrypt, bench_aes128_cbc_decrypt);
criterion_main!(benches);
