// ------------------------------------------------------------------------
// HeavyThing Rust translation — AES-128-CBC throughput benchmark
// Copyright © 2015 2 Ton Digital, Jeff Marrison <jeff@2ton.com.au>
// Homepage: https://2ton.com.au/
//
// This file is part of the HeavyThing Rust translation.
//
// HeavyThing is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// HeavyThing is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with the HeavyThing library. If not, see <https://www.gnu.org/licenses/>.
// ------------------------------------------------------------------------
//
// aes_cbc.rs: Criterion benchmark for AES-128-CBC encryption / decryption
//             throughput.
//
// Source: exercises Rust code at `crates/heavything/src/crypto/aes.rs`
// that replaces `aes.inc` (1,423 lines: AES-NI hardware path + Wei Dai
// public-domain software fallback). The Rust port delegates to the
// `aes` + `cbc` RustCrypto crates (constant-time, FIPS 197-compliant)
// because `ring` does not expose raw AES-CBC (AAP §0.7.2.2).
//
// AAP §0.8.5 mandates this benchmark as part of the Gate 3 deliverable
// (`BENCHMARK_REPORT.md`): the Rust implementation MUST sustain AES-128-CBC
// throughput within 3× of the assembly baseline (AAP §0.8.1). The bench
// produces raw measurements only; the assembly-vs-Rust comparison table
// is generated by a sibling agent that runs the assembly binaries (see
// AAP §0.8.5 baseline save/compare workflow).
//
// Input sizes (per agent_prompt MUST set spanning L1 → L2 → L3 → RAM):
//   * 1 KiB   — typical HTTP request / SSH packet; fits in L1
//   * 64 KiB  — bridges TLS max record (16 KiB) and asset chunks; L2
//   * 1 MiB   — large messages; L3 cache regime
//   * 16 MiB  — bulk transfer; main-memory bandwidth regime
//
// Runs:
//   cargo bench --bench aes_cbc -p heavything
//
// Baseline save/compare:
//   cargo bench --bench aes_cbc -p heavything -- --save-baseline rust_v1
//   cargo bench --bench aes_cbc -p heavything -- --baseline rust_v1
//
// CRITICAL CONSTRAINT (per AAP §0.6.3.3 / §0.8.7): the workspace pins
// `criterion = "0.5"` WITHOUT the `async_tokio` feature. AES is purely
// CPU-bound so no tokio bridge is required here — the bench is fully
// synchronous (`b.iter(|| ...)`) and never awaits.

#![forbid(unsafe_code)]
#![allow(clippy::unwrap_used)]
#![allow(clippy::expect_used)]

use std::time::Duration;

use criterion::{black_box, criterion_group, criterion_main, BenchmarkId, Criterion, Throughput};

use heavything::crypto::aes::{
    aes128_cbc_new_decrypt, aes128_cbc_new_encrypt, aesni_available, AES128_KEY_SIZE, BLOCK_SIZE,
};

// ============================================================================
// Module-level constants — deterministic key / IV / size set.
// ============================================================================

/// AES-128 input sizes covered by the benchmark.
///
/// Every size is a multiple of 16 (the AES block size) so that the
/// CBC `encrypt_blocks` / `decrypt_blocks` API contract (input length
/// MUST be a multiple of `BLOCK_SIZE`) is satisfied without padding
/// (no PKCS#7 — SSH/TLS framing policy, AAP §0.8 / `aes.inc`).
///
/// The four sizes span the L1 → L2 → L3 → main-memory cache hierarchy
/// per the agent_prompt MUST set ("test at least the sizes 1 KiB,
/// 64 KiB, 1 MiB, 16 MiB"):
///
/// * `1_024` — 1 KiB; sits comfortably in L1 (~32 KiB on Intel Core /
///   Xeon, similar on AMD Zen). Captures the per-call dispatch overhead
///   — typical HTTP request and SSH channel-data packet sizes.
/// * `65_536` — 64 KiB; pushes into L2 (256 KiB - 1 MiB on most server
///   CPUs). Bridges TLS 1.2's 16 KiB max record (RFC 5246 §6.2.1) and
///   the larger static-asset chunks served by `webserver`.
/// * `1_048_576` — 1 MiB; works the L3 cache (typically 4 MiB+ on
///   shared-cache server-class parts).
/// * `16_777_216` — 16 MiB; main-memory bandwidth regime. AES-NI
///   saturation point on a single core (~1 GiB/s).
const INPUT_SIZES: &[usize] = &[1_024, 65_536, 1_048_576, 16_777_216];

/// AES-128 key from NIST Special Publication 800-38A appendix F.2.1
/// (CBC-AES128.Encrypt example).
///
/// The full 16-byte hex value is `2b7e151628aed2a6abf7158809cf4f3c`,
/// which is **the** canonical AES-128 example key used throughout the
/// NIST test vectors (FIPS-197, SP 800-38A, SP 800-38C, SP 800-38D).
///
/// Choosing a NIST-canonical key (rather than an arbitrary string)
/// satisfies CP8 review finding MINOR #2 by making the bench fixture
/// fully traceable to a published reference: any reviewer can verify
/// the bench's key-schedule output against the NIST appendix without
/// having to derive a custom round-key table from scratch.
///
/// Hardcoded (not random) so runs are reproducible across CI and local
/// dev — key-schedule cost is amortized to zero by the `b.iter()`
/// harness regardless of which key is used, but reproducibility lets
/// downstream agents capture-and-compare baselines deterministically.
const KEY: [u8; AES128_KEY_SIZE] = [
    0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c,
];

/// AES-CBC initial value (IV) from NIST SP 800-38A appendix F.2.1.
///
/// The full 16-byte hex value is `000102030405060708090a0b0c0d0e0f`,
/// the canonical IV that pairs with [`KEY`] in the SP 800-38A worked
/// example. Combined with [`KEY`], this IV produces the published
/// reference ciphertext (see [`NIST_F21_PLAINTEXT`] /
/// [`NIST_F21_CIPHERTEXT`] below) — the [`kat_assertion`] sanity
/// check verifies the bench's encryption path matches the reference
/// output before each run, so any future divergence (e.g. a key-schedule
/// bug introduced into `crypto::aes`) is caught at the bench fixture
/// level rather than producing silently-incorrect throughput numbers.
const IV: [u8; BLOCK_SIZE] = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
];

/// NIST SP 800-38A appendix F.2.1 plaintext — four 16-byte blocks.
///
/// Each block is one of the canonical AES sample plaintext blocks used
/// across the NIST publications:
///   block 1: `6bc1bee22e409f96e93d7e117393172a`
///   block 2: `ae2d8a571e03ac9c9eb76fac45af8e51`
///   block 3: `30c81c46a35ce411e5fbc1191a0a52ef`
///   block 4: `f69f2445df4f9b17ad2b417be66c3710`
///
/// These are the canonical SP 800-38A appendix-F plaintext blocks used
/// across §F.1 (ECB), §F.2 (CBC), §F.3 (CFB), §F.4 (OFB), and §F.5
/// (CTR), so any reviewer already familiar with the NIST
/// modes-of-operation publication can recognise them on sight. The
/// exact byte values match the in-tree round-trip test
/// [`crate::crypto::aes::tests::aes128_cbc_nist_sp800_38a_vector`]
/// (the array literal at `crates/heavything/src/crypto/aes.rs:1032`),
/// which is the project's authoritative AES-128-CBC NIST-vector
/// fixture.
const NIST_F21_PLAINTEXT: [u8; 64] = [
    0x6b, 0xc1, 0xbe, 0xe2, 0x2e, 0x40, 0x9f, 0x96, 0xe9, 0x3d, 0x7e, 0x11, 0x73, 0x93, 0x17, 0x2a, 0xae,
    0x2d, 0x8a, 0x57, 0x1e, 0x03, 0xac, 0x9c, 0x9e, 0xb7, 0x6f, 0xac, 0x45, 0xaf, 0x8e, 0x51, 0x30, 0xc8,
    0x1c, 0x46, 0xa3, 0x5c, 0xe4, 0x11, 0xe5, 0xfb, 0xc1, 0x19, 0x1a, 0x0a, 0x52, 0xef, 0xf6, 0x9f, 0x24,
    0x45, 0xdf, 0x4f, 0x9b, 0x17, 0xad, 0x2b, 0x41, 0x7b, 0xe6, 0x6c, 0x37, 0x10,
];

/// NIST SP 800-38A appendix F.2.1 ciphertext — four 16-byte blocks.
///
/// The published reference ciphertext for [`NIST_F21_PLAINTEXT`] under
/// [`KEY`] + [`IV`]:
///   block 1: `7649abac8119b246cee98e9b12e9197d`
///   block 2: `5086cb9b507219ee95db113a917678b2`
///   block 3: `73bed6b8e3c1743b7116e69e22229516`
///   block 4: `3ff1caa1681fac09120eca307586e1a7`
///
/// `kat_assertion()` (called once at the start of `bench_aes128_cbc_encrypt`)
/// verifies that the heavything AES-128-CBC encrypt path produces this
/// exact ciphertext for the NIST plaintext. If the assertion ever fails,
/// the bench panics IMMEDIATELY rather than producing silently-wrong
/// throughput numbers — preserving Gate 3 measurement integrity.
const NIST_F21_CIPHERTEXT: [u8; 64] = [
    0x76, 0x49, 0xab, 0xac, 0x81, 0x19, 0xb2, 0x46, 0xce, 0xe9, 0x8e, 0x9b, 0x12, 0xe9, 0x19, 0x7d, 0x50,
    0x86, 0xcb, 0x9b, 0x50, 0x72, 0x19, 0xee, 0x95, 0xdb, 0x11, 0x3a, 0x91, 0x76, 0x78, 0xb2, 0x73, 0xbe,
    0xd6, 0xb8, 0xe3, 0xc1, 0x74, 0x3b, 0x71, 0x16, 0xe6, 0x9e, 0x22, 0x22, 0x95, 0x16, 0x3f, 0xf1, 0xca,
    0xa1, 0x68, 0x1f, 0xac, 0x09, 0x12, 0x0e, 0xca, 0x30, 0x75, 0x86, 0xe1, 0xa7,
];

// ============================================================================
// Known-Answer Test (KAT) — verifies the bench fixture produces NIST F.2.1
// ciphertext before any throughput measurement runs.
// ============================================================================

/// Run the NIST SP 800-38A appendix F.2.1 known-answer test against
/// the heavything AES-128-CBC implementation.
///
/// This is a one-shot integrity check — NOT a throughput measurement.
/// Called once at the start of [`bench_aes128_cbc_encrypt`]; if the
/// assertion fails, the bench panics before any measurement starts, so
/// reviewers can never publish throughput numbers from a broken AES
/// implementation. This satisfies the second part of CP8 review finding
/// MINOR #2 ("plus a one-time KAT assertion that the encryption produces
/// the published SP 800-38A reference ciphertext").
///
/// The KAT runs in `< 1 µs` (encrypts 4 blocks then compares), so it
/// adds no measurable overhead to the bench launch.
fn kat_assertion() {
    let mut buf = NIST_F21_PLAINTEXT;
    let mut enc = aes128_cbc_new_encrypt(&KEY, &IV)
        .expect("KAT: aes128_cbc_new_encrypt with NIST F.2.1 KEY+IV must succeed");
    enc.encrypt_blocks(&mut buf)
        .expect("KAT: AES-128-CBC encrypt_blocks on NIST F.2.1 plaintext must succeed");
    assert_eq!(
        buf, NIST_F21_CIPHERTEXT,
        "AES-128-CBC NIST SP 800-38A F.2.1 KAT FAILED — \
         heavything::crypto::aes is producing incorrect ciphertext. \
         Bench refusing to run; fix the AES implementation before \
         publishing throughput numbers (review finding MINOR #2)."
    );
}

// ============================================================================
// Helper — populate a vector with deterministic non-zero plaintext.
// ============================================================================

/// Build a `Vec<u8>` of length `size` filled with a deterministic
/// non-trivial pattern.
///
/// A pure-zero buffer would let CPU branch-predictors / data-prefetchers
/// optimize the inner loop in unrealistic ways, biasing the measurement
/// downward. The `(i * 31 + 7) & 0xff` pattern is the same one used by
/// `tests/net_integration.rs` Section 6 (TCP echo) and matches the
/// FASM `aes_test_*` plaintext generation convention.
fn make_plaintext(size: usize) -> Vec<u8> {
    debug_assert_eq!(
        size % BLOCK_SIZE,
        0,
        "AES-CBC bench plaintext length MUST be a multiple of {} bytes",
        BLOCK_SIZE
    );
    let mut buf = vec![0u8; size];
    for (i, b) in buf.iter_mut().enumerate() {
        *b = ((i.wrapping_mul(31).wrapping_add(7)) & 0xff) as u8;
    }
    buf
}

// ============================================================================
// Benchmark — AES-128-CBC encryption throughput.
// ============================================================================

/// Measure AES-128-CBC encryption throughput at every input size in
/// [`INPUT_SIZES`].
///
/// Each iteration:
///   1. Constructs a fresh `Aes128Cbc` encryptor (key-schedule + IV setup
///      via `cbc::Encryptor::<Aes128>::new`). The constructor cost is
///      included in the iteration so the headline number is
///      end-to-end "encrypt N bytes from cold" — matching what the
///      FASM `aes$encrypt_init + aes$encrypt` flow measures.
///   2. Calls `encrypt_blocks` on a mutable copy of the plaintext.
///   3. Discards the ciphertext via [`black_box`] to prevent the
///      compiler optimizing away the encryption step.
///
/// Criterion is configured with `Throughput::Bytes(size)` so the
/// reported value is in bytes/second (the headline metric for
/// crypto bandwidth).
///
/// Sample size is the criterion default (100) for sizes ≤ 64 KiB, and
/// reduced to 50 for the 1 MiB and 16 MiB sizes — those iterations are
/// slow enough that the default would target an unreasonable wall-clock
/// duration per benchmark. The reduction is the same accommodation
/// applied in `bench_http_concurrent` (`http_roundtrip.rs`).
fn bench_aes128_cbc_encrypt(c: &mut Criterion) {
    // ---- KAT integrity check -------------------------------------
    // Before any throughput measurement runs, verify that the
    // heavything AES-128-CBC encrypt path produces the NIST SP 800-38A
    // appendix F.2.1 reference ciphertext for the NIST plaintext under
    // the NIST KEY+IV. If this assertion fails, the bench panics
    // before publishing any numbers — see [`kat_assertion`] for
    // rationale. (CP8 review finding MINOR #2.)
    kat_assertion();

    // Report runtime CPU AES-NI capability once per process invocation
    // (printed to stderr so it does not pollute criterion's stdout
    // benchmark report). Per AAP §0.1.1 implicit requirement, AES-NI
    // detection is runtime, not compile-time; this annotation lets the
    // sibling agent populating `BENCHMARK_REPORT.md` (Gate 3) label
    // each measurement set with the host's `has_aesni` status so the
    // assembly-vs-Rust comparison is apples-to-apples (both use AES-NI
    // when available, both use the software fallback otherwise).
    eprintln!("aes128_cbc_throughput: has_aesni = {}", aesni_available());

    let mut group = c.benchmark_group("aes_cbc/encrypt/aes128");
    group.warm_up_time(Duration::from_secs(3));
    group.measurement_time(Duration::from_secs(5));

    for &size in INPUT_SIZES {
        // Pre-generate the plaintext outside the iter loop so allocation
        // cost is amortized to zero. Per-iteration we clone into a
        // working buffer (clone cost is included in the measurement,
        // matching the FASM `aes$encrypt`'s in-place-on-caller-buffer
        // semantic where the caller copies from a source buffer).
        let plaintext = make_plaintext(size);

        // Sample size: criterion default (100) for ≤ 64 KiB, reduced to
        // 50 for ≥ 1 MiB so that the wall-clock per benchmark stays in
        // a reasonable range (16 MiB at ~1 GiB/s × 50 samples ≈ 800 ms
        // baseline plus warm-up + measurement).
        if size >= 1_048_576 {
            group.sample_size(50);
        } else {
            group.sample_size(100);
        }

        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::from_parameter(size), &plaintext, |b, plaintext| {
            b.iter(|| {
                let mut buf = plaintext.clone();
                let mut enc = aes128_cbc_new_encrypt(&KEY, &IV)
                    .expect("aes128_cbc_new_encrypt should succeed for valid key + IV");
                enc.encrypt_blocks(black_box(&mut buf))
                    .expect("AES-128-CBC encrypt_blocks should succeed");
                // `black_box` consumes the ciphertext so the compiler
                // cannot eliminate the round-key writes or the
                // encryption inner loop.
                black_box(buf);
            });
        });
    }

    group.finish();
}

// ============================================================================
// Benchmark — AES-128-CBC decryption throughput.
// ============================================================================

/// Measure AES-128-CBC decryption throughput at every input size in
/// [`INPUT_SIZES`].
///
/// Mirrors [`bench_aes128_cbc_encrypt`] but exercises the
/// [`cbc::Decryptor::<Aes128>`] code path via
/// [`heavything::crypto::aes::aes128_cbc_new_decrypt`]. The decryption
/// inverse-key-schedule cost is included per-iteration for the same
/// "from cold" measurement convention.
///
/// In practice CBC decryption is fully parallelizable across blocks
/// (every block depends only on the previous ciphertext block, not the
/// previous plaintext), so AES-NI hardware achieves higher decryption
/// throughput than encryption. The bench reports both sides so the
/// asymmetry is visible in `BENCHMARK_REPORT.md`.
fn bench_aes128_cbc_decrypt(c: &mut Criterion) {
    let mut group = c.benchmark_group("aes_cbc/decrypt/aes128");
    group.warm_up_time(Duration::from_secs(3));
    group.measurement_time(Duration::from_secs(5));

    for &size in INPUT_SIZES {
        // Construct the ciphertext once via a one-shot encrypt path.
        // The decryption iter loop does NOT include the encryption
        // setup in its measurement — only the decryption work itself,
        // which is the property under measurement.
        let plaintext = make_plaintext(size);
        let mut enc = aes128_cbc_new_encrypt(&KEY, &IV)
            .expect("aes128_cbc_new_encrypt setup for decrypt-bench fixture");
        let mut ciphertext = plaintext;
        enc.encrypt_blocks(&mut ciphertext)
            .expect("encrypt_blocks setup for decrypt-bench fixture");

        // Sample size: 100 for ≤ 64 KiB, 50 for ≥ 1 MiB (mirrors the
        // encrypt-side accommodation; see [`bench_aes128_cbc_encrypt`]).
        if size >= 1_048_576 {
            group.sample_size(50);
        } else {
            group.sample_size(100);
        }

        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::from_parameter(size), &ciphertext, |b, ciphertext| {
            // Use `iter_batched` so the per-iteration ciphertext
            // clone is performed in the SETUP phase (untimed) rather
            // than inside the timed region. `BatchSize::LargeInput`
            // tells criterion to allocate buffers on a per-batch
            // basis with sensible heap-pressure heuristics for
            // multi-MiB working sets — appropriate for the 1 MiB
            // and 16 MiB sizes in `INPUT_SIZES` per criterion 0.5
            // documentation.
            b.iter_batched(
                || ciphertext.clone(),
                |mut buf| {
                    let mut dec = aes128_cbc_new_decrypt(&KEY, &IV)
                        .expect("aes128_cbc_new_decrypt should succeed for valid key + IV");
                    dec.decrypt_blocks(black_box(&mut buf))
                        .expect("AES-128-CBC decrypt_blocks should succeed");
                    // Return the buffer through `black_box` so the
                    // compiler cannot elide the round-key reads or
                    // the inverse-S-box lookups inside the inner
                    // loop. Returning (rather than just calling
                    // `black_box(&buf)` and dropping) keeps the
                    // optimizer maximally pessimistic about the
                    // buffer's observability.
                    black_box(buf)
                },
                criterion::BatchSize::LargeInput,
            );
        });
    }

    group.finish();
}

// ============================================================================
// Criterion entry-points.
//
// `criterion_group!` aggregates the encrypt + decrypt benchmark
// functions. `criterion_main!` synthesises the `fn main()` entry that
// `cargo bench --bench aes_cbc` invokes (the `[[bench]]` entry in
// `crates/heavything/Cargo.toml` sets `harness = false`, deferring to
// criterion's harness instead of the default libtest harness).
// ============================================================================

criterion_group!(benches, bench_aes128_cbc_encrypt, bench_aes128_cbc_decrypt);
criterion_main!(benches);
