// ------------------------------------------------------------------------
// HeavyThing Rust translation — SHA-256 throughput benchmark
// Copyright © 2015 2 Ton Digital, Jeff Marrison <jeff@2ton.com.au>
// Homepage: https://2ton.com.au/
//
// This file is part of the HeavyThing Rust translation.
//
// HeavyThing is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// HeavyThing is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with the HeavyThing library. If not, see <https://www.gnu.org/licenses/>.
// ------------------------------------------------------------------------
//
// sha256.rs: Criterion benchmark for SHA-256 hashing throughput.
//
// Source: exercises Rust code at `crates/heavything/src/crypto/sha2.rs`
// that replaces `sha2.inc` (2,146 lines: software SHA-256 + SHA-512 +
// SHA-NI hardware path). The Rust port delegates to `ring 0.17`
// (`ring::digest::SHA256`) which performs runtime CPU dispatch between
// SHA-NI / AVX2 / portable code paths — matching the FASM `sha256$init +
// sha256$transform` runtime CPUID-based dispatch.
//
// AAP §0.8.5 mandates this benchmark as part of the Gate 3 deliverable
// (`BENCHMARK_REPORT.md`): the Rust implementation MUST sustain SHA-256
// throughput within 3× of the assembly baseline (AAP §0.8.1). The bench
// produces raw measurements only; the assembly-vs-Rust comparison table
// is generated by a sibling agent that runs the assembly binaries.
//
// Two benchmark variants:
//
//   * Oneshot   — `heavything::crypto::sha2::sha256(data)` returns the
//                 32-byte digest in a single call. Matches the FASM
//                 `sha256$once` shape (init → update(data) → final).
//   * Streaming — `Sha256::new()` + `update()` + `finalize()`, with
//                 `update` called once with the full slice. This
//                 surfaces any per-call overhead between the two paths
//                 (the cost of constructing the streaming hasher).
//
// Input sizes (per AAP §0.8.5 protocol harmonization):
//   * 64 B    — SHA-256 single-block (block size = 64 bytes).
//   * 1 KiB   — typical HTTP request hash / SSH packet HMAC body.
//   * 16 KiB  — TLS 1.2 record-size analogue.
//   * 256 KiB — large message / file-content hash chunk.
//   * 1 MiB   — bulk-content regime; SHA-NI saturation point.
//
// Runs:
//   cargo bench --bench sha256 -p heavything
//
// Baseline save/compare:
//   cargo bench --bench sha256 -p heavything -- --save-baseline rust_v1
//   cargo bench --bench sha256 -p heavything -- --baseline rust_v1
//
// CRITICAL CONSTRAINT (per AAP §0.6.3.3 / §0.8.7): the workspace pins
// `criterion = "0.5"` WITHOUT the `async_tokio` feature. SHA-256 is
// purely CPU-bound so no tokio bridge is required here — the bench is
// fully synchronous (`b.iter(|| ...)`) and never awaits.

#![forbid(unsafe_code)]
#![allow(clippy::unwrap_used)]
#![allow(clippy::expect_used)]

use std::time::Duration;

use criterion::{
    black_box, criterion_group, criterion_main, BenchmarkId, Criterion, Throughput,
};

use heavything::crypto::sha2::{sha256, Sha256};

// ============================================================================
// Module-level constants — input sizes mirroring the AES-CBC bench.
// ============================================================================

/// SHA-256 input sizes covered by the benchmark.
///
/// Per AAP §0.8.5 the bench surfaces both small-message and bulk-hash
/// throughput regimes. Sizes are deliberately identical to the
/// AES-128-CBC bench (`aes_cbc.rs`) so that BENCHMARK_REPORT.md can
/// pair the two side-by-side at every operating point.
///
/// * `64`         — SHA-256 single 512-bit block (no buffering).
/// * `1024`       — typical HTTP request body / SSH packet payload.
/// * `16384`      — TLS 1.2 record-size analogue (RFC 5246 §6.2.1).
/// * `262_144`    — large static-asset chunk.
/// * `1_048_576`  — bulk-transfer regime; SHA-NI saturation point.
const INPUT_SIZES: &[usize] = &[64, 1024, 16_384, 262_144, 1_048_576];

// ============================================================================
// Helper — populate a vector with deterministic non-zero input bytes.
// ============================================================================

/// Build a `Vec<u8>` of length `size` filled with a deterministic
/// non-trivial pattern.
///
/// A pure-zero buffer would let CPU branch-predictors / data-prefetchers
/// optimize the inner loop in unrealistic ways, biasing the measurement
/// downward. The `(i * 31 + 7) & 0xff` pattern is the same one used by
/// `aes_cbc.rs` and `tests/net_integration.rs` Section 6 (TCP echo).
fn make_input(size: usize) -> Vec<u8> {
    let mut buf = vec![0u8; size];
    for (i, b) in buf.iter_mut().enumerate() {
        *b = ((i.wrapping_mul(31).wrapping_add(7)) & 0xff) as u8;
    }
    buf
}

// ============================================================================
// Benchmark — SHA-256 oneshot throughput (`sha256(data) -> [u8; 32]`).
// ============================================================================

/// Measure SHA-256 throughput via the oneshot
/// [`heavything::crypto::sha2::sha256`] free function.
///
/// Each iteration calls `sha256(data)` exactly once. Internally `ring`
/// constructs a fresh `digest::Context`, feeds the entire slice in a
/// single `update`, and finalizes — there is no per-iteration heap
/// allocation in the hot path (the `Context` lives on the stack).
///
/// Criterion is configured with `Throughput::Bytes(size)` so the
/// reported value is in bytes/second (the headline metric for hash
/// bandwidth).
///
/// Sample size is 100 (criterion default) for sizes ≤ 16 KiB, and
/// reduced to 50 for the two largest sizes to keep the per-bench
/// wall-clock reasonable. Same convention as `aes_cbc.rs` and
/// `http_roundtrip.rs`.
fn bench_sha256_oneshot(c: &mut Criterion) {
    let mut group = c.benchmark_group("sha256/oneshot");
    group.warm_up_time(Duration::from_secs(3));
    group.measurement_time(Duration::from_secs(5));

    for &size in INPUT_SIZES {
        // Pre-generate the input outside the iter loop so allocation cost
        // is amortized to zero and the bench measures pure hash cost.
        let input = make_input(size);

        if size >= 262_144 {
            group.sample_size(50);
        } else {
            group.sample_size(100);
        }

        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::from_parameter(size), &input, |b, input| {
            b.iter(|| {
                // `black_box` on the input prevents the compiler hoisting
                // the hash out of the iter loop (deterministic input
                // would otherwise constant-fold). `black_box` on the
                // output prevents elimination of the digest computation.
                let digest = sha256(black_box(input.as_slice()));
                black_box(digest);
            });
        });
    }

    group.finish();
}

// ============================================================================
// Benchmark — SHA-256 streaming throughput (`Sha256::update` + `finalize`).
// ============================================================================

/// Measure SHA-256 throughput via the streaming
/// [`heavything::crypto::sha2::Sha256`] hasher.
///
/// Each iteration:
///   1. Constructs a fresh `Sha256` (key-schedule equivalent: zero
///      since SHA-256 has no per-key state).
///   2. Calls `update` once with the full input slice.
///   3. Calls `finalize` (which consumes `self`).
///   4. `black_box`-discards the digest.
///
/// The construction + `finalize` overhead is included in the iteration
/// time, surfacing any per-call cost between this path and the
/// oneshot path. For small inputs (e.g., 64 B) the construction
/// overhead is a measurable fraction of the iteration; for large
/// inputs (e.g., 1 MiB) it is negligible. The pair of measurements
/// allows BENCHMARK_REPORT.md to characterise both regimes.
fn bench_sha256_streaming(c: &mut Criterion) {
    let mut group = c.benchmark_group("sha256/streaming");
    group.warm_up_time(Duration::from_secs(3));
    group.measurement_time(Duration::from_secs(5));

    for &size in INPUT_SIZES {
        let input = make_input(size);

        if size >= 262_144 {
            group.sample_size(50);
        } else {
            group.sample_size(100);
        }

        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::from_parameter(size), &input, |b, input| {
            b.iter(|| {
                let mut hasher = Sha256::new();
                hasher.update(black_box(input.as_slice()));
                let digest = hasher.finalize();
                black_box(digest);
            });
        });
    }

    group.finish();
}

// ============================================================================
// Benchmark — chunked-update streaming (multiple update() calls per hash).
//
// Models the realistic "hash-while-streaming-from-network" pattern used
// by the SSH transport (`net::ssh::cipher`): each packet's payload is
// fed to the integrity hasher in one or more `update` calls before
// `finalize`. This bench surfaces the partial-block buffering overhead
// inside `ring::digest::Context`.
// ============================================================================

/// Chunk size used by [`bench_sha256_chunked`].
///
/// 256 bytes mirrors the SSH transport's typical per-packet payload
/// granularity (`SSH_PACKET_SIZE_DEFAULT` is on the order of 32 KiB but
/// payloads are framed in smaller chunks at the channel layer).
const CHUNK_SIZE: usize = 256;

/// Measure SHA-256 throughput when the input is fed in fixed-size
/// chunks via repeated `update` calls.
///
/// Chunked feeding is the realistic pattern for streaming protocols
/// (SSH transport integrity, HTTP chunked-transfer hash verification).
/// Compared to the single-`update` streaming benchmark, this one
/// exercises the partial-block buffer logic inside
/// `ring::digest::Context::update` and surfaces any cost asymmetry
/// between contiguous and chunked feeding.
///
/// For inputs smaller than `CHUNK_SIZE` (only `64 B` in our matrix)
/// the bench degenerates to a single `update` call — i.e., it
/// converges to the streaming benchmark above. That's intentional and
/// expected: BENCHMARK_REPORT.md should observe near-identical timings
/// at 64 B between `streaming/64` and `chunked/64`.
fn bench_sha256_chunked(c: &mut Criterion) {
    let mut group = c.benchmark_group("sha256/chunked");
    group.warm_up_time(Duration::from_secs(3));
    group.measurement_time(Duration::from_secs(5));

    for &size in INPUT_SIZES {
        let input = make_input(size);

        if size >= 262_144 {
            group.sample_size(50);
        } else {
            group.sample_size(100);
        }

        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::from_parameter(size), &input, |b, input| {
            b.iter(|| {
                let mut hasher = Sha256::new();
                for chunk in input.chunks(CHUNK_SIZE) {
                    hasher.update(black_box(chunk));
                }
                let digest = hasher.finalize();
                black_box(digest);
            });
        });
    }

    group.finish();
}

// ============================================================================
// Criterion entry-points.
//
// `criterion_group!` aggregates the three benchmark functions. The
// trio gives BENCHMARK_REPORT.md (Gate 3) a complete view of SHA-256
// throughput across the three realistic call patterns: oneshot,
// single-update streaming, and chunked streaming.
// `criterion_main!` synthesises the `fn main()` entry that
// `cargo bench --bench sha256` invokes (the `[[bench]]` entry in
// `crates/heavything/Cargo.toml` sets `harness = false`, deferring to
// criterion's harness instead of the default libtest harness).
// ============================================================================

criterion_group!(
    benches,
    bench_sha256_oneshot,
    bench_sha256_streaming,
    bench_sha256_chunked
);
criterion_main!(benches);
