// ------------------------------------------------------------------------
// HeavyThing Rust translation — SHA-256 throughput benchmark
// Copyright © 2015 2 Ton Digital, Jeff Marrison <jeff@2ton.com.au>
// Homepage: https://2ton.com.au/
//
// This file is part of the HeavyThing Rust translation.
//
// HeavyThing is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// HeavyThing is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with the HeavyThing library. If not, see <https://www.gnu.org/licenses/>.
// ------------------------------------------------------------------------
//
// sha256.rs: Criterion benchmark for SHA-256 hashing throughput.
//
// Source: exercises Rust code at `crates/heavything/src/crypto/sha2.rs`
// that translates `sha2.inc` (2,146 lines: software SHA-256 + SHA-512 +
// optional SHA-NI hardware path). Algorithm derivation per `sha2.inc`
// lines 22–30: "translated loosely from some of the public domain goods
// from Wei Dai". The Rust port delegates to `ring 0.17`
// (`ring::digest::SHA256`) which performs runtime CPU dispatch between
// SHA-NI / AVX2 / portable code paths — matching the FASM `sha256$init +
// sha256$transform` runtime CPUID-based dispatch.
//
// AAP §0.8.5 mandates this benchmark as part of the Gate 3 deliverable
// (`BENCHMARK_REPORT.md`): the Rust implementation MUST sustain SHA-256
// throughput within 3× of the assembly baseline (AAP §0.8.1). The bench
// produces raw measurements only; the assembly-vs-Rust comparison table
// is generated by a sibling agent that runs the assembly binaries.
//
// Two benchmark variants per AAP Phase 4 / Phase 5:
//
//   * Oneshot   — `heavything::crypto::sha2::sha256(data)` returns the
//                 32-byte digest in a single call. Matches the FASM
//                 `sha256$once` shape (init → update(data) → final).
//                 This is the common case for most callers.
//   * Streaming — `Sha256::new()` + repeated `update()` + `finalize()`,
//                 with the input fed in 4 KiB chunks. Models the
//                 realistic "hash-while-streaming-from-network"
//                 pattern used by the SSH transport
//                 (`net::ssh::cipher`) and HTTP chunked-transfer
//                 hash verification. Surfaces the partial-block
//                 buffering overhead inside `ring::digest::Context`.
//
// Input sizes (per AAP §0.7.5 hard rule — at least 1 KiB, 64 KiB, 1 MiB,
// 16 MiB, 64 MiB; 64 MiB is the headline size):
//   * 64 B      — exactly one SHA-256 block (single-block diagnostic).
//   * 1 KiB     — typical HTTP request hash / SSH packet HMAC body.
//   * 64 KiB    — TLS 1.2 record-size analogue (RFC 5246 §6.2.1).
//   * 1 MiB     — bulk-content regime; SHA-NI saturation point.
//   * 16 MiB    — RAM-bandwidth-limited regime.
//   * 64 MiB    — headline size; converges on the upper-bound
//                 throughput where compression-function cost is fully
//                 amortized over memory-bandwidth limits.
//
// Runs:
//   cargo bench --bench sha256 -p heavything
//
// Baseline save/compare:
//   cargo bench --bench sha256 -p heavything -- --save-baseline rust_v1
//   cargo bench --bench sha256 -p heavything -- --baseline rust_v1
//
// CRITICAL CONSTRAINT (per AAP §0.6.3.3 / §0.8.7): the workspace pins
// `criterion = "0.5"` WITHOUT the `async_tokio` feature. SHA-256 is
// purely CPU-bound so no tokio bridge is required here — the bench is
// fully synchronous (`b.iter(|| ...)`) and never awaits.

#![forbid(unsafe_code)]
#![allow(clippy::unwrap_used)]
#![allow(clippy::expect_used)]

use std::time::Duration;

use criterion::{black_box, criterion_group, criterion_main, BenchmarkId, Criterion, Throughput};

use heavything::crypto::sha2::{sha256, Sha256};

// ============================================================================
// Module-level constants — input sizes covering single-block, cache-resident,
// and RAM-bandwidth-limited regimes per AAP §0.7.5 hard rule.
// ============================================================================

/// Benchmarked payload sizes in bytes.
///
/// Captures single-block (64 B), L1/L2 cache residency (1 KiB, 64 KiB),
/// L3 pressure (1 MiB), and RAM-bandwidth-limited (16 MiB, 64 MiB)
/// regimes per AAP §0.7.5. The 64 MiB size is the headline figure in
/// `BENCHMARK_REPORT.md` because it converges on the SHA-NI peak
/// throughput where the compression-function cost is fully amortized
/// against memory bandwidth.
///
/// Rationale per size:
/// * `64` — exactly one SHA-256 block (FIPS 180-4 §5.1.1, 512-bit /
///   64-byte block size); diagnostic for per-call overhead vs
///   compression-function cost.
/// * `1024` — 1 KiB; typical HTTP request body / SSH packet payload.
/// * `64 * 1024` — 64 KiB; TLS 1.2 record-size analogue (RFC 5246
///   §6.2.1 max plaintext fragment is 16 KiB but rwasa's mimelike
///   chunk size is 65,535 bytes per `webserver.inc`; 64 KiB is the
///   closest power-of-two).
/// * `1024 * 1024` — 1 MiB; bulk-content regime; SHA-NI compression
///   function saturates the L1/L2 cache-line refill rate around this
///   size.
/// * `16 * 1024 * 1024` — 16 MiB; well beyond L3 cache; throughput
///   here is RAM-bandwidth-bound on most modern x86_64 CPUs.
/// * `64 * 1024 * 1024` — 64 MiB (headline); converges on the upper
///   bound where compression-function cost is fully amortized against
///   memory-bandwidth limits.
const INPUT_SIZES: &[usize] = &[
    64,
    1024,
    64 * 1024,
    1024 * 1024,
    16 * 1024 * 1024,
    64 * 1024 * 1024,
];

/// Chunk size for the streaming benchmark — 4 KiB matches typical
/// page-aligned I/O (e.g., reading from disk or TCP in 4 KiB
/// increments per the Linux page granularity).
///
/// A different chunk size would measure different real-world
/// workloads; 4 KiB is the canonical I/O-streaming chunk.
const CHUNK_SIZE: usize = 4 * 1024;

// ============================================================================
// Helper — populate a vector with deterministic non-zero input bytes.
// ============================================================================

/// Build a `Vec<u8>` of length `size` filled with a deterministic
/// non-trivial byte pattern.
///
/// A pure-zero buffer would let CPU branch-predictors / data-prefetchers
/// optimize the inner loop in unrealistic ways, biasing the measurement
/// downward. The `(i & 0xff) as u8` pattern produces the byte sequence
/// 0, 1, 2, …, 255, 0, 1, … — non-constant but reproducible across
/// runs. The same approach is used by the sibling `aes_cbc.rs`
/// benchmark for cross-bench input-pattern parity.
///
/// `black_box` on the input slice (inside each `b.iter` closure) is the
/// authoritative guarantee against constant-folding; the non-trivial
/// pattern is defense-in-depth in case `black_box` ever loses its
/// optimization-barrier semantics.
fn make_input(size: usize) -> Vec<u8> {
    (0..size).map(|i| (i & 0xff) as u8).collect()
}

// ============================================================================
// Benchmark — SHA-256 oneshot throughput (`sha256(data) -> [u8; 32]`).
// ============================================================================

/// Measure SHA-256 throughput via the oneshot
/// [`heavything::crypto::sha2::sha256`] free function — the common
/// case for most callers (single complete buffer to hash).
///
/// Each iteration calls `sha256(data)` exactly once. Internally `ring`
/// constructs a fresh `digest::Context`, feeds the entire slice in a
/// single `update`, and finalizes — there is no per-iteration heap
/// allocation in the hot path (the `Context` lives on the stack).
///
/// Criterion is configured with `Throughput::Bytes(size)` so the
/// reported value is in bytes/second (the headline metric for hash
/// bandwidth).
///
/// Sample size is criterion's default 100 for sizes < 1 MiB, reduced
/// to 50 for 1 MiB / 16 MiB to keep per-bench wall-clock under
/// ~10 seconds, and further reduced to the criterion minimum of 10
/// for the 64 MiB headline size where each iteration is the
/// dominant cost. Same convention as the sibling `aes_cbc.rs` and
/// `http_roundtrip.rs` benchmarks.
///
/// SHA-NI is detected and dispatched automatically by `ring` at
/// runtime — there is no public API in `heavything::crypto::sha2` to
/// query this (unlike `crypto::aes::aesni_available`). The eprintln
/// at the head of this function records the algorithm in stderr for
/// `BENCHMARK_REPORT.md` annotation.
fn bench_sha256_oneshot(c: &mut Criterion) {
    eprintln!("sha256_throughput: using ring::digest::SHA256 (SHA-NI handled by ring)");

    let mut group = c.benchmark_group("sha256_throughput/oneshot");
    group.warm_up_time(Duration::from_secs(3));
    group.measurement_time(Duration::from_secs(5));

    for &size in INPUT_SIZES {
        // Pre-generate the input outside the iter loop so allocation
        // cost is amortized to zero and the bench measures pure hash
        // cost.
        let input = make_input(size);

        // Adaptive sample-size: criterion's default 100 samples is
        // fine for fast sizes; reduce for larger sizes to keep total
        // wall-clock per group reasonable.
        if size >= 64 * 1024 * 1024 {
            // criterion's documented minimum sample_size is 10.
            group.sample_size(10);
        } else if size >= 1024 * 1024 {
            group.sample_size(50);
        } else {
            group.sample_size(100);
        }

        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::from_parameter(size), &input, |b, input| {
            b.iter(|| {
                // `black_box` on the input prevents the compiler from
                // hoisting the hash out of the iter loop (deterministic
                // input would otherwise constant-fold). `black_box` on
                // the output prevents elimination of the digest
                // computation. Both are mandatory per AAP hard rule.
                let digest = sha256(black_box(input.as_slice()));
                black_box(digest);
            });
        });
    }

    group.finish();
}

// ============================================================================
// Benchmark — SHA-256 streaming/chunked throughput.
//
// Models the realistic "hash-while-streaming-from-network" pattern
// used by the SSH transport (`net::ssh::cipher`) integrity layer and
// HTTP chunked-transfer hash verification: the input is fed to the
// hasher in fixed-size chunks via repeated `update` calls before the
// terminal `finalize`. This bench surfaces the partial-block
// buffering overhead inside `ring::digest::Context::update` and any
// per-call cost asymmetry between contiguous (oneshot) and chunked
// feeding.
// ============================================================================

/// Measure SHA-256 throughput when the input is fed in fixed-size
/// 4 KiB chunks via repeated `Sha256::update` calls.
///
/// Each iteration:
///   1. Constructs a fresh `Sha256` (no per-key state — SHA-256 has
///      no key).
///   2. Feeds the input slice in `CHUNK_SIZE`-sized chunks via a
///      loop over `slice::chunks`. The final chunk may be shorter
///      than `CHUNK_SIZE` if the size is not a multiple of 4 KiB.
///   3. Calls `finalize` (which consumes `self` to statically
///      prevent use-after-finalize bugs — see [`Sha256::finalize`]
///      docs for the FASM `sha256$final` parity discussion).
///   4. `black_box`-discards the digest so the compiler cannot
///      eliminate the computation as dead code.
///
/// # Why a subset of `INPUT_SIZES`?
///
/// For inputs smaller than `CHUNK_SIZE` (4 KiB), the chunked feed
/// degenerates to a single `update` call — exactly redundant with
/// the oneshot benchmark above. To avoid duplicate measurements,
/// this bench only exercises sizes ≥ `CHUNK_SIZE`. The 64 KiB
/// minimum here gives at least 16 chunks per input, which is
/// enough to surface the partial-block buffering cost
/// realistically.
fn bench_sha256_streaming(c: &mut Criterion) {
    let mut group = c.benchmark_group("sha256_throughput/streaming");
    group.warm_up_time(Duration::from_secs(3));
    group.measurement_time(Duration::from_secs(5));

    // Streaming is meaningful only for sizes large enough to be
    // chunked (≥ CHUNK_SIZE). For smaller inputs the chunked path is
    // identical to a single `update` call, so we omit them here per
    // AAP Phase 5 design rationale.
    let streaming_sizes: &[usize] = &[64 * 1024, 1024 * 1024, 16 * 1024 * 1024, 64 * 1024 * 1024];

    for &size in streaming_sizes {
        let input = make_input(size);

        if size >= 64 * 1024 * 1024 {
            group.sample_size(10);
        } else if size >= 1024 * 1024 {
            group.sample_size(50);
        } else {
            group.sample_size(100);
        }

        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::from_parameter(size), &input, |b, input| {
            b.iter(|| {
                let mut hasher = Sha256::new();
                // Chunked update simulating streamed I/O: 4 KiB at
                // a time. `black_box` on each chunk prevents the
                // compiler from peeling the loop and reducing the
                // hash to a precomputed constant.
                for chunk in input.chunks(CHUNK_SIZE) {
                    hasher.update(black_box(chunk));
                }
                let digest = hasher.finalize();
                black_box(digest);
            });
        });
    }

    group.finish();
}

// ============================================================================
// Criterion entry-points.
//
// `criterion_group!` aggregates the two benchmark functions per AAP
// Phase 6. The pair gives `BENCHMARK_REPORT.md` (Gate 3) a complete
// view of SHA-256 throughput across the two realistic call patterns:
// oneshot (free function) and streaming (chunked-update).
// `criterion_main!` synthesises the `fn main()` entry that
// `cargo bench --bench sha256` invokes (the `[[bench]]` entry in
// `crates/heavything/Cargo.toml` sets `harness = false`, deferring to
// criterion's harness instead of the default libtest harness).
// ============================================================================

criterion_group!(benches, bench_sha256_oneshot, bench_sha256_streaming);
criterion_main!(benches);
